#!/usr/bin/env node

var exec = require('child_process').exec

exec('.bin/server',
  function (error, stdout, stderr) {
    console.log('stdout: ' + stdout)
    console.log('stderr: ' + stderr)
    if (error !== null) {
      console.log('exec error: ' + error)
    }
})

console.log('server started at http://localhost:8080...')

exec('./node_modules/webpack/bin/webpack.js -p --progress --colors --devtool sourcemap --watch',
  function (error, stdout, stderr) {
    console.log('stdout: ' + stdout)
    console.log('stderr: ' + stderr)
    if (error !== null) {
      console.log('exec error: ' + error)
    }
})

console.log('webpack running in watch mode...')
