#!/usr/bin/env node

var express = require('express');
var app = express();
var App = require('../app');

go();

function go() {
  app.get('/', App.home);
  app.get('/search', App.search);

  console.log('starting server...');

  server = app.listen('8080', function () {
    var
      host = server.address().address,
      port = server.address().port;
      
    console.log('app listening at http://%s:%s', host, port);
  });
}

