#!/usr/bin/env node

var exec = require('child_process').exec

exec('.bin/create_server', function (error, stdout, stderr) {
  console.log('stdout: ' + stdout)
  console.log('stderr: ' + stderr)
  if (error !== null) {
    console.log('exec error: ' + error)
  }
})

console.log('server running...');

exec('./node_modules/webpack/bin/webpack.js --progress --colors --watch --debug --output-pathinfo',
  function (error, stdout, stderr) {
    console.log('stdout: ' + stdout)
    console.log('stderr: ' + stderr)
    if (error !== null) {
      console.log('exec error: ' + error)
    }
})

console.log('webpack running in watch mode...')
